/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathtutor;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo ThinkPad L520
 */
public class Menu extends javax.swing.JFrame {
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrac = new javax.swing.JMenu();
        jPracAdd = new javax.swing.JMenuItem();
        jPracSub = new javax.swing.JMenuItem();
        jPracMulti = new javax.swing.JMenuItem();
        jPracDiv = new javax.swing.JMenuItem();
        jPracExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jAddTest = new javax.swing.JMenuItem();
        jTestSub = new javax.swing.JMenuItem();
        jTestMulti = new javax.swing.JMenuItem();
        jTestDiv = new javax.swing.JMenuItem();
        jTestExit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jManageUser = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jManageReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(235, 232, 232));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (3).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenuPrac.setText("Practice Mode");

        jPracAdd.setText("Addition");
        jPracAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPracAddActionPerformed(evt);
            }
        });
        jMenuPrac.add(jPracAdd);

        jPracSub.setText("Subtraction");
        jPracSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPracSubActionPerformed(evt);
            }
        });
        jMenuPrac.add(jPracSub);

        jPracMulti.setText("Multiplication");
        jPracMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPracMultiActionPerformed(evt);
            }
        });
        jMenuPrac.add(jPracMulti);

        jPracDiv.setText("Division");
        jPracDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPracDivActionPerformed(evt);
            }
        });
        jMenuPrac.add(jPracDiv);

        jPracExit.setText("Exit");
        jPracExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPracExitActionPerformed(evt);
            }
        });
        jMenuPrac.add(jPracExit);

        jMenuBar1.add(jMenuPrac);

        jMenu3.setText("Testing Mode");

        jAddTest.setText("Addition");
        jAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddTestActionPerformed(evt);
            }
        });
        jMenu3.add(jAddTest);

        jTestSub.setText("Subtraction");
        jTestSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestSubActionPerformed(evt);
            }
        });
        jMenu3.add(jTestSub);

        jTestMulti.setText("Multiplication");
        jTestMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestMultiActionPerformed(evt);
            }
        });
        jMenu3.add(jTestMulti);

        jTestDiv.setText("Division");
        jTestDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestDivActionPerformed(evt);
            }
        });
        jMenu3.add(jTestDiv);

        jTestExit.setText("Exit");
        jTestExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestExitActionPerformed(evt);
            }
        });
        jMenu3.add(jTestExit);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Add User");

        jManageUser.setText("Manage User");
        jManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManageUserActionPerformed(evt);
            }
        });
        jMenu4.add(jManageUser);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("View Report");

        jManageReport.setText("Manage Report");
        jManageReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManageReportActionPerformed(evt);
            }
        });
        jMenu5.add(jManageReport);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPracAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPracAddActionPerformed
        // TODO add your handling code here:
         try 
        {
            new PracMode().setVisible(true);
            //PracMode.AdditionPractice();
            PracMode.Mode("Add");
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch 
    }//GEN-LAST:event_jPracAddActionPerformed

    private void jPracSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPracSubActionPerformed
        // TODO add your handling code here:
         try 
        {
            new PracMode().setVisible(true);
            //PracMode.SubtractionPractice();
            PracMode.Mode("Sub");
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch 
    }//GEN-LAST:event_jPracSubActionPerformed

    private void jPracMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPracMultiActionPerformed
        // TODO add your handling code here:
         try 
        {
            new PracMode().setVisible(true);
            PracMode.MultiplicationPractice();
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch 
    }//GEN-LAST:event_jPracMultiActionPerformed

    private void jAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddTestActionPerformed
        // TODO add your handling code here:
         try 
        {
            new TestMode().setVisible(true);
            TestMode.Mode("Add");
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch /
        
    }//GEN-LAST:event_jAddTestActionPerformed

    private void jTestSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestSubActionPerformed
        // TODO add your handling code here:
         try 
        {
            new TestMode().setVisible(true);
            TestMode.Mode("Sub");
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch 
    }//GEN-LAST:event_jTestSubActionPerformed

    private void jTestMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestMultiActionPerformed
        // TODO add your handling code here:
         try 
        {
            new TestMode().setVisible(true);
            TestMode.Mode("Multi");
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch 
    }//GEN-LAST:event_jTestMultiActionPerformed

    private void jTestDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestDivActionPerformed
        // TODO add your handling code here:
         try 
        {
            new TestMode().setVisible(true);
            TestMode.Mode("Div");
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch 
    }//GEN-LAST:event_jTestDivActionPerformed

    private void jManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManageUserActionPerformed
        // TODO add your handling code here:
        try
        {
            new AddUser().setVisible(true);
            this.dispose();
        } // end try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch // end catch

    }//GEN-LAST:event_jManageUserActionPerformed

    private void jManageReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManageReportActionPerformed
        // TODO add your handling code here:
        try
        {
            new Report().setVisible(true);
            this.dispose();
        } // end try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        }
    }//GEN-LAST:event_jManageReportActionPerformed

    private void jPracDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPracDivActionPerformed
        // TODO add your handling code here:
         try 
        {
            new PracMode().setVisible(true);
            PracMode.DivisionPractice();
            this.dispose();
        } // end try
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(Menu.this, e.getMessage());
        } // end catch // end catch
    }//GEN-LAST:event_jPracDivActionPerformed

    private void jPracExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPracExitActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Are You Sure","Select an Option",JOptionPane.YES_NO_OPTION);
        if (i==0)
        {
            JOptionPane.showMessageDialog(null,"Thank you for using Maths Tutor Programme.");
            this.dispose();
        }
    }//GEN-LAST:event_jPracExitActionPerformed

    private void jTestExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestExitActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Are You Sure","Select an Option",JOptionPane.YES_NO_OPTION);
        if (i==0)
        {
            JOptionPane.showMessageDialog(null,"Thank you for using Maths Tutor Programme.");
            this.dispose();
        }
    }//GEN-LAST:event_jTestExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
//    public static int SubMenu()
//    {
//        
//        int userInput = 0;
//        noQuestions= JOptionPane.showInputDialog(null, "How many Practice Questions do you want for this Session? ");
//        return userInput= Integer.parseInt(noQuestions);
//         
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAddTest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jManageReport;
    private javax.swing.JMenuItem jManageUser;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuPrac;
    public static javax.swing.JMenuItem jPracAdd;
    public static javax.swing.JMenuItem jPracDiv;
    private javax.swing.JMenuItem jPracExit;
    public static javax.swing.JMenuItem jPracMulti;
    public static javax.swing.JMenuItem jPracSub;
    private javax.swing.JMenuItem jTestDiv;
    private javax.swing.JMenuItem jTestExit;
    private javax.swing.JMenuItem jTestMulti;
    private javax.swing.JMenuItem jTestSub;
    // End of variables declaration//GEN-END:variables
}

